basePath: /api
info:
  contact:
    email: 52553624@qq.com
    name: hxl
  description: This is an API for Fiber Admin Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Fiber Admin App
  version: "1.0"
paths: {}
swagger: "2.0"
