basePath: /api
definitions:
  controller.BadRequestErrorResponse:
    properties:
      details:
        additionalProperties: true
        description: 具体错误详情（可选）
        type: object
      error:
        description: 错误信息
        type: string
    type: object
  controller.InternalServerErrorResponse:
    properties:
      details:
        additionalProperties: true
        description: 具体错误详情（可选）
        type: object
      error:
        description: 错误信息
        type: string
    type: object
  controller.UserLoginReq:
    properties:
      password:
        description: |-
          密码
          required: true
          example: 123456
        type: string
      username:
        description: |-
          用户名
          required: true
          example: admin
        type: string
    type: object
  controller.UserReq:
    properties:
      password:
        description: |-
          密码
          required: true
          example: 123456
        type: string
      username:
        description: |-
          用户名
          required: true
          example: admin
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  model.User:
    properties:
      avatar:
        description: |-
          Avatar URL of the user
          example: http://xx
          required: false
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      email:
        description: |-
          Email of the user
          format: email
          required: false
        type: string
      id:
        type: integer
      nickname:
        description: |-
          Nickname of the user
          example: JohnDoe
          required: false
        type: string
      password:
        description: |-
          Password of the user
          required: true
        type: string
      phone:
        description: |-
          Phone number of the user
          format: int64
          required: false
        type: string
      updatedAt:
        type: string
      username:
        description: |-
          Username of the user
          example: xxxxx
          required: true
        type: string
    type: object
info:
  contact:
    email: 52553624@qq.com
    name: hxl
  description: This is an API for Fiber Admin Application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Fiber Admin App
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功创建用户并返回新创建的用户信息
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: 请求错误，例如缺少必填字段或格式不正确
          schema:
            $ref: '#/definitions/controller.BadRequestErrorResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller.InternalServerErrorResponse'
      summary: 登录
      tags:
      - 用户管理
  /user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            type: string
        "400":
          description: 请求错误
          schema:
            type: string
        "500":
          description: 内部错误
          schema:
            type: string
    post:
      consumes:
      - application/json
      description: 创建一个新的系统用户
      parameters:
      - description: 用户信息
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/controller.UserReq'
      produces:
      - application/json
      responses:
        "200":
          description: 成功创建用户并返回新创建的用户信息
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: 请求错误，例如缺少必填字段或格式不正确
          schema:
            $ref: '#/definitions/controller.BadRequestErrorResponse'
        "500":
          description: 服务器内部错误
          schema:
            $ref: '#/definitions/controller.InternalServerErrorResponse'
      summary: 创建用户
      tags:
      - 用户管理
swagger: "2.0"
